### ISSUE TITLE
Is there some example PHP code coming soon?

### ISSUE THREAD

**Issue by amandoabreu** [idfy-io/idfy-sdk-php#1]
To facilitate getting started and doing some sanity checks it would be nice to have examples. I'm assuming you might have something already done so if it's low effort it would be great :)

**Comment by Slettan** [comment]
Hello @amandoabreu. The PHP SDK is still a work in progress. When v1 is ready it will be made available on Packagist, but we don't have an ETA yet.

You could always write the HTTP code yourself and integrate with our APIs directly. API reference can be found [here](https://developer.idfy.io/api). Feel free to contact [support@idfy.io](mailto:support@idfy.io) if you need help or have any questions.

**Comment by amandoabreu** [comment]
Thanks for the answer on a Saturday night! It's going alright using guzzle for the time being and looking at the .NET stuff for some guidance.
